# Generated by Django 5.0.2 on 2024-02-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BbForm',
            new_name='Bb',
        ),
    ]
